export enum Status {
    OK = 'OK',
    CREATED = 'CREATED',
    BAD_REQUEST = 'BAD REQUEST',
    MISSING_PARAMETERS = 'MISSING PARAMETERS',
    NOT_FOUND = 'NOT FOUND',
    INTERNAL_SERVER_ERROR = 'INTERNAL SERVER_ERROR'
}